### PR TITLE
Building with Responsive Design

### PR DESCRIPTION
**Pull request by ozovalihasan**
Milestones:

-- aligned elements using float, flex or grid.
-- used the mobile-first approach to build a responsive website.
.
The goal was to develop a responsive webpage by using media queries.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @ozovalihasan and @krys2fa :clap: :clap: :1st_place_medal: :1st_place_medal: :1st_place_medal: 
#### You did an excellent job :muscle: . This is an incredible job. I don't know how you guys work but I must say that you display mastery in this project.

#### This project is approved :star2: :100: :star2:

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Comment by ozovalihasan** [comment]
Thanks for the approval @lekegitrepo

**Comment by krys2fa** [comment]
Feedback and approval are much-appreciated @lekegitrepo.

**Pull request merged**
